### ISSUE TITLE
Update fastai

### ISSUE THREAD

**Issue by rlds-107** [drivendataorg/sfp-cervical-biopsy-runtime#17]
@pjbull Please confirm if the submission scoring system was updated with pr #15. It still shows fastai version 2.0.0 on the live system.

**Comment by pjbull** [comment]
@rlds-107, thanks. We're investigating the issue and should have an update soon.

**Comment by pjbull** [comment]
Should be fixed now, if you want to confirm @rlds-107

**Comment by rlds-107** [comment]
Confirmed. Thanks @pjbull !
