### ISSUE TITLE
add package ipython

### ISSUE THREAD

**Issue by LifeIsTwoShort** [drivendataorg/sfp-cervical-biopsy-runtime#20]
I'm trying keep same fastai2 and pytorch vision with requirement. When I submit I get this error:

<img width="957" alt="截屏2020-10-07 下午10 25 25" src="https://user-images.githubusercontent.com/71064553/95344489-49e54b80-08ec-11eb-8997-31bd34933ef6.png">
 
I don't know the specific reason. It may have something to do with my jupyter working environment. When I try to uninstall ipython package, I can generate the same error locally. I am very new to git, and I tried git clone this repo, the speed is too slow, so I can not take a PR. Can anyone help me add this library (ipython-7.18.1, old version is also work), thanks!

I am eager to fix this problem! Thanks!

**Comment by r-b-g-b** [comment]
I am not very familiar with fastai, but just browsing the docs, it seems that `Learner.export` and `load_learner` might be trying to save/load things from your local environment. https://docs.fast.ai/learner#Exporting-a-Learner

> Warning: load_learner requires all your custom code be in the exact same place as when exporting your Learner (the main script, or the module you imported it from).

This makes me think that a model saved with `Learner.export` will not load in another runtime (in the Docker container, for instance). That is consistent with the error you are seeing -- `IPython` is present in your local training environment, but not in the official runtime. I'd suggest looking into another way to save and load your model that works across runtimes. https://docs.fast.ai/learner#Serializing Maybe using `Learner.save` and `Learner.load`.

Again, I'm not very familiar with fastai -- if this doesn't help you might try asking for help on the fastai forums or stackoverflow. Good luck!

**Comment by LifeIsTwoShort** [comment]
> I am not very familiar with fastai, but just browsing the docs, it seems that `Learner.export` and `load_learner` might be trying to save/load things from your local environment. https://docs.fast.ai/learner#Exporting-a-Learner
> 
> > Warning: load_learner requires all your custom code be in the exact same place as when exporting your Learner (the main script, or the module you imported it from).
> 
> This makes me think that a model saved with `Learner.export` will not load in another runtime (in the Docker container, for instance). That is consistent with the error you are seeing -- `IPython` is present in your local training environment, but not in the official runtime. I'd suggest looking into another way to save and load your model that works across runtimes. https://docs.fast.ai/learner#Serializing Maybe using `Learner.save` and `Learner.load`.
> 
> Again, I'm not very familiar with fastai -- if this doesn't help you might try asking for help on the fastai forums or stackoverflow. Good luck!

Thank you very much, I will try it! 👍

**Comment by LifeIsTwoShort** [comment]
> I am not very familiar with fastai, but just browsing the docs, it seems that `Learner.export` and `load_learner` might be trying to save/load things from your local environment. https://docs.fast.ai/learner#Exporting-a-Learner
> 
> > Warning: load_learner requires all your custom code be in the exact same place as when exporting your Learner (the main script, or the module you imported it from).
> 
> This makes me think that a model saved with `Learner.export` will not load in another runtime (in the Docker container, for instance). That is consistent with the error you are seeing -- `IPython` is present in your local training environment, but not in the official runtime. I'd suggest looking into another way to save and load your model that works across runtimes. https://docs.fast.ai/learner#Serializing Maybe using `Learner.save` and `Learner.load`.
> 
> Again, I'm not very familiar with fastai -- if this doesn't help you might try asking for help on the fastai forums or stackoverflow. Good luck!

It works.........Thanks a lot!❤️
